apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flowpay-be-client-tls
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStoreName }}
  data:
    - secretKey: server.crt
      remoteRef:
        key: server-cert
    - secretKey: server.key
      remoteRef:
        key: server-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-cert
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStoreName }}
  data:
    - secretKey: ca.crt
      remoteRef:
        key: ca-cert