apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
spec:
  project: default
  source:
    chart: docker-registry
    repoURL: https://helm.twun.io
    targetRevision: 2.2.2
    helm:
      releaseName: docker-registry
      parameters:
        - name: "ingress.enabled"
          value: "true"
        - name: "ingress.className"
          value: nginx-private
        - name: "ingres.hosts[0]"
          value: registry.nebojsa-test.store

  destination:
    server: "https://kubernetes.default.svc"
    namespace: docker-registry
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true