apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:                                                  
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: external-secrets/gcpsm-secret                        
              key: secret-access-credentials                              
        projectID: arus-401310