apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificate-signer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Nebojsa92/certificate-signer.git"
    targetRevision: main
    path: chart/
    # helm:
    #   valueFiles:
    #     - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: certificate-signer
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m