apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flowpay-be-admin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # repoURL: "https://github.com/arus-consulting/flowpay-be.git"
    # targetRevision: main
    # path: chart/
    repoUrl: "https://github.com/Nebojsa92/arus-gitops.git"
    path: projects/flowpay/apps/flowpay-be-admin/
    helm:
      valueFiles:
        - values.yaml
        - values-admin.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: flowpay-be-admin
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m