apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flowpay-be-client
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Nebojsa92/arus-gitops.git"
    path: projects/flowpay/apps/flowpay-be-client/
    helm:
      valueFiles:
        - values.yaml
        - values-client.yaml
    # repoURL: "https://github.com/arus-consulting/flowpay-be.git"
    # targetRevision: main
    # path: chart/
    # helm:
    #   valueFiles:
    #     - values.yaml
    #     - values-client.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: flowpay-be-client
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m