{{- if gt (len (default list .Values.secretEnv)) 0 }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStoreName }}          
  data:                                                       
  {{- range .Values.secretEnv }}
    - secretKey: {{ .name }} 
      remoteRef:            
        key: {{ .remoteRefKey }}
  {{- end }}
{{- end }}

{{- if gt (len (default list .Values.secretFiles)) 0 }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}-secret-files
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStoreName }}
  data:
  {{- range .Values.secretFiles }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .remoteRefKey }}
  {{- end }}
{{- end }}
