{{- if and .Values.secretEnv (gt (len .Values.secretEnv) 0) }}
apiVersion: kubernetes-client.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStoreName }}          
  data:                                                       
  {{- range .Values.secretEnv }}
    - secretKey: {{ .name }} 
      remoteRef:            
        key: {{ .remoteRefKey }}
  {{- end }}
{{- end }}

{{- if and .Values.secretFiles (gt (len .Values.secretFiles) 0) }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}-secret-files
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStoreName }}
  data:
  {{- range .Values.secretFiles }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .remoteRefKey }}
  {{- end }}
{{- end }}
