apiVersion: v2
name: certificate-signer
description: A Helm chart for the Certificate Signer application
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: api
    version: 0.1.0
    repository: "file://../../charts/api"